# Generated by Django 4.2.7 on 2023-11-27 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_mng', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Conformed', 'Conformed'), ('Delivered', 'Delevered'), ('Cancelled', 'Cancelled')], default='New', max_length=10),
        ),
    ]
