# Generated by Django 4.2.7 on 2023-11-27 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order_mng', '0003_alter_order_order_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='order_total',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
