# Generated by Django 4.2.7 on 2023-12-04 09:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon_Mng', '0002_coupon_is_active'),
        ('order_mng', '0006_remove_orderaddress_order_alter_order_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coupen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coupon_Mng.coupon'),
        ),
    ]
