# Generated by Django 4.2.7 on 2023-12-09 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_mng', '0007_order_coupen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='amount_paid',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='status',
        ),
    ]
