# Generated by Django 4.2.7 on 2023-12-09 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('order_mng', '0008_remove_payment_amount_paid_remove_payment_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderproduct',
            name='Payment',
        ),
    ]
