# Generated by Django 4.2.7 on 2023-11-18 07:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('house_name', models.CharField(max_length=40)),
                ('streat_name', models.CharField(max_length=50)),
                ('post_office', models.CharField(max_length=20)),
                ('place', models.CharField(max_length=25)),
                ('district', models.CharField(max_length=20)),
                ('state', models.CharField(max_length=30)),
                ('country', models.CharField(blank=True, max_length=35, null=True)),
            ],
        ),
    ]
