# Generated by Django 4.2.7 on 2023-11-18 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0004_alter_accountuser_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
