# Generated by Django 4.2.7 on 2023-11-18 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0005_address_pincode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accountuser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='static/image_admin/people'),
        ),
    ]
