# Generated by Django 4.2.7 on 2023-11-19 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0010_remove_address_user_account_address_account_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='address',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='user_log.address'),
        ),
    ]
