# Generated by Django 4.2.7 on 2023-12-09 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_log', '0014_wallet_wallethistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wallet',
            name='balance',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='wallethistory',
            name='amount',
            field=models.IntegerField(),
        ),
    ]
