# Generated by Django 4.2.7 on 2023-11-13 18:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_det', '0003_atribute_atribute_value_product_product_variant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product_variant',
            name='product_variant_slug',
            field=models.SlugField(blank=True, max_length=200),
        ),
    ]
