# Generated by Django 4.2.7 on 2023-12-04 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_det', '0005_product_product_offer'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='offer_expairy',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
