# Generated by Django 4.2.7 on 2023-12-18 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_det', '0006_product_offer_expairy'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_variant',
            name='thumbnail_image',
        ),
    ]
