# Generated by Django 4.2.7 on 2023-11-23 15:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_det', '0004_alter_product_variant_product_variant_slug'),
        ('user_product_mng', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cartitem',
            name='product',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product_variant',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='product_det.product_variant'),
            preserve_default=False,
        ),
    ]
