# Generated by Django 4.2.7 on 2023-11-24 04:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('product_det', '0004_alter_product_variant_product_variant_slug'),
        ('user_product_mng', '0002_remove_cartitem_product_cartitem_product_variant'),
    ]

    operations = [
        migrations.AddField(
            model_name='cartitem',
            name='color',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_color', to='product_det.atribute_value'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='size',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cart_size', to='product_det.atribute_value'),
        ),
    ]
