# Generated by Django 4.2.7 on 2023-12-04 08:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Coupon_Mng', '0001_initial'),
        ('user_product_mng', '0006_alter_cartitem_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='coupen',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Coupon_Mng.coupon'),
        ),
    ]
